# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A function to generate Markov chains using Rcpp
#' @description A function to generate Markov chains using Rcpp given the variance of the normal distribution, the initial value and the length of the chain.
#' @param sigma The variance of the normal distribution
#' @param x0 The initial value
#' @param N The length of the chain
#' @return a Markov chain with length \code{N}
#' @examples 
#' \dontrun{
#' sigma=1
#' x1=0
#' N=2000
#' X=LARMC(sigma,x0,N)
#' plot(x)
#' }
#' @export
LARMC <- function(sigma, x0, N) {
    .Call('_StatComp20087_LARMC', PACKAGE = 'StatComp20087', sigma, x0, N)
}

